name: PR Perf
on:
  issue_comment:
    types: [created]
    branches: [main]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: Release

jobs:
  test_perf:
    # if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/perf-run') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        c_compiler: [gcc, clang, cl]
        exclude:
        - os: ubuntu-latest
          c_compiler: cl
        - os: macos-latest
          c_compiler: cl
        - os: windows-latest
          c_compiler: gcc
        - os: windows-latest
          c_compiler: clang

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake 
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE 
      
      - name: Build library
        shell: bash
        run: cmake --build ./build --config $BUILD_TYPE