name: PR Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  INSTALL_PREFIX: /usr
  BUILD_TYPE: Release

jobs:
  build_test_on_windows:
    permissions:
      contents: write
    strategy:
      matrix:
        arch: [x64, arm64]
        c_compiler: [cl]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC ARM64 Toolchain
      if: ${{ matrix.arch == 'arm64' }}
      shell: pwsh
      run: |
        echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsamd64_arm64.bat" >> $env:GITHUB_ENV \
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsamd64_arm64.bat"

    - name: Configure CMake 
      shell: bash
      run: |
        mkdir build
        cd build
        cmake .. \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
        -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} \
        -A ${{ matrix.arch }}
    
    - name: Build library
      shell: bash
      run: cmake --build ./build --config $BUILD_TYPE

    - name: Test library 
      shell: bash
      run: ./build/test/Release/test.exe
    